"""Stage 5 - code generation: AST -> .zas assembly text.

Every expression is compiled for one of three TARGETS:
    None      the value is not needed (statement context)
    "var"     a variable token: "sp" (push), ".LOCAL" or "GLOBAL"
    RETURN    the value is the routine's result (last form of a ROUTINE)

Conditions are compiled differently: compile_cond(e, label, jump_if)
emits code that jumps to `label` when the condition's truth == jump_if.
So <COND (<EQUAL? .X 1> ...)> becomes a single `je .X 1 ?~next`, never a
0/1 value that is then tested (proforma §11: predicates are BRANCHES).

Operand order and the stack: operands are read left to right, and each
"sp" operand POPS. If two operands both need code, the earlier one is put
in a hidden temporary local (.$T1, .$T2...) so that the pops come out in
the right order. See `operands`.
"""
from __future__ import annotations

from zforge.common.opcodes import BY_NAME
from zforge.compiler import ast
from zforge.compiler.diagnostics import Diagnostics
from zforge.compiler.semantic import ENTRY_ROUTINE, MAX_LOCALS, Symbols

RETURN = object()           # the "return this value" target
SCRATCH = "$SCRATCH"        # a hidden global for values nobody wants


def asm_string(text: str) -> str:
    """Quote text for .zas: \\ and " are escaped, ^ is a newline."""
    body = text.replace("\\", "\\\\").replace('"', '\\"').replace("^", "\\^")
    return '"' + body.replace("\n", "^") + '"'


def asm_word(word: str) -> str:
    return "'" + word.replace("\\", "\\\\").replace("'", "\\'") + "'"


class CodeGenerator:
    def __init__(self, program: ast.Program, symbols: Symbols, diag: Diagnostics,
                 filename: str = "<zil>"):
        self.p = program
        self.s = symbols
        self.diag = diag
        self.filename = filename
        self.out: list[str] = []
        self.arrays: list[str] = []

    def error(self, node, message: str) -> None:
        self.diag.error(node.loc, message)

    # ================================================================ program
    def generate(self) -> str:
        o = self.out
        o.append(f"; generated by zforge from {self.filename} - ZIL-lite -> Z-machine v5")
        o += [".release 1", '.serial "000000"', f".main {ENTRY_ROUTINE}", ""]
        o.append(f".global {SCRATCH} 0                 ; compiler scratch variable")
        for g in self.p.globals:
            o.append(f".global {g.name} {self.data_token(g.init)}")
        o.append("")
        o.append("; FLAGS -> attribute numbers (§12.3.1), properties -> numbers (§12.4)")
        for name, number in self.s.flags.items():
            o.append(f".constant {name} {number}")
        for name, number in self.s.properties.items():
            o.append(f".constant P?{name} {number}")
        for c in self.p.constants:
            value = self.constant_number(c.value)
            if value is not None:
                o.append(f".constant {c.name} {value}")
        for pd in self.p.propdefs:
            o.append(f".propdefault P?{pd.name} {self.data_token(pd.default)}")
        o.append("")
        self.objects()
        for r in self.p.routines:
            self.routine(r)
        o += self.arrays
        return "\n".join(o) + "\n"

    def objects(self) -> None:
        for name, (_number, obj) in self.s.objects.items():
            desc = obj.desc if obj.desc is not None else name.lower().replace("-", " ")
            opts = []
            if obj.parent:
                opts.append(f"parent={obj.parent}")
            if obj.flags:
                opts.append("attrs=" + ",".join(f for f, _loc in obj.flags))
            self.out.append(f".object {name} {asm_string(desc)} {' '.join(opts)}".rstrip())
            if obj.synonyms:
                words = " ".join(map(asm_word, obj.synonyms))
                self.out.append(f".prop {name} P?SYNONYM {words}")
            if obj.adjectives:
                words = " ".join(map(asm_word, obj.adjectives))
                self.out.append(f".prop {name} P?ADJECTIVE {words}")
            for prop, value in obj.properties:
                if value.kind == "to":        # an exit: 1 byte = the room number
                    self.out.append(f".propb {name} P?{prop} {value.values[0]}")
                else:
                    tokens = " ".join(self.data_token(v) for v in value.values)
                    self.out.append(f".prop {name} P?{prop} {tokens}")
        self.out.append("")

    # ------------------------------------------------------- constant data
    def constant_number(self, e) -> int | None:
        """A CONSTANT's numeric value (strings are inlined where used)."""
        if isinstance(e, ast.Num):
            return e.value
        if isinstance(e, ast.False_):
            return 0
        if isinstance(e, ast.Global):
            kind = self.s.kind_of(e.name)
            if kind == "constant":
                return self.constant_number(self.s.constants[e.name].value)
            if kind == "object":
                return self.s.objects[e.name][0]
            if kind == "flag":
                return self.s.flags[e.name]
        if isinstance(e, ast.Str):
            return None
        self.error(e, "a CONSTANT must be a number, a string or ,NAME")
        return None

    def data_token(self, e) -> str:
        """A token for DATA (global initial values, properties, tables)."""
        if isinstance(e, (ast.Num, ast.Str, ast.Word, ast.False_, ast.Table)):
            return self.value_token(e)
        if isinstance(e, ast.Global):
            return self.value_token(e)
        if isinstance(e, ast.Atom) and e.name == "T":
            return "1"
        self.error(e, "only constants (numbers, strings, ,NAMES, W?WORDS, tables) "
                      "are allowed here")
        return "0"

    def table(self, e: ast.Table) -> str:
        kind = "byte" if e.byte else "word"
        if e.kind == "ITABLE":
            count = self.constant_number(e.items[0]) if e.items else 0
            init = self.data_token(e.items[1]) if len(e.items) > 1 else "0"
            items = [init] * (count or 0)
        else:
            items = [self.data_token(i) for i in e.items]
            if e.kind == "LTABLE":
                items = [str(len(items))] + items
        # Named only now: the items may be tables themselves, and they must
        # be numbered first or an inner table would get this table's name.
        name = f"$TABLE{len(self.arrays) + 1}"
        self.arrays.append(f".array {name} {kind} {' '.join(items)}".rstrip())
        return name

    # ============================================================== routines
    def routine(self, r: ast.RoutineDecl) -> None:
        self.r = r
        self.lines: list[str] = []
        self.labels = 0
        self.temps_free: list[str] = []
        self.temp_count = 0
        self.loops: list[tuple[str, str, object]] = []   # (start, end, target)
        # "OPT" defaults: only when the caller did not pass the argument
        for i, (name, default) in enumerate(r.optionals):
            if default is not None:
                have = self.new_label()
                self.emit(f"check_arg_count {len(r.params) + i + 1} ?{have}")
                self.compile(default, "." + name)
                self.place(have)
        for name, default in r.auxes:          # "AUX" defaults: always
            if default is not None:
                self.compile(default, "." + name)
        if not r.body:
            self.emit("rtrue")
        for e in r.body[:-1]:
            self.compile(e, None)
        if r.body:
            self.compile(r.body[-1], RETURN)
        names = ["." + n for n in r.local_names()]
        names += [f".$T{i + 1}" for i in range(self.temp_count)]
        if len(names) > MAX_LOCALS:
            self.error(r, f"{r.name} needs {len(names)} locals including temporaries; "
                          "the Z-machine allows 15 - simplify nested expressions")
        self.out.append(f".routine {r.name} {' '.join(names)}".rstrip())
        self.out += self.lines
        self.out += [".end", ""]

    # ---------------------------------------------------------------- helpers
    def emit(self, text: str) -> None:
        self.lines.append("    " + text)

    def new_label(self) -> str:
        self.labels += 1
        return f"_{self.labels}"

    def place(self, label: str) -> None:
        self.lines.append(f"{label}:")

    def temp(self) -> str:
        if self.temps_free:
            return self.temps_free.pop()
        self.temp_count += 1
        return f".$T{self.temp_count}"

    def free(self, temps: list[str]) -> None:
        self.temps_free.extend(reversed(temps))

    @staticmethod
    def branch(label: str, on_true: bool) -> str:
        return f"?{label}" if on_true else f"?~{label}"

    def is_simple(self, e) -> bool:
        """Simple = usable directly as an operand, no code needed."""
        return isinstance(e, (ast.Num, ast.Str, ast.Local, ast.Global, ast.Word,
                              ast.False_, ast.Table)) or \
            (isinstance(e, ast.Atom) and e.name == "T")

    def value_token(self, e) -> str:
        if isinstance(e, ast.Num):
            return str(e.value)
        if isinstance(e, ast.Str):
            return asm_string(e.value)
        if isinstance(e, ast.Local):
            return "." + e.name
        if isinstance(e, ast.Word):
            return asm_word(e.word)
        if isinstance(e, ast.False_):
            return "0"
        if isinstance(e, ast.Atom):
            return "1"                          # T
        if isinstance(e, ast.Table):
            return self.table(e)
        if isinstance(e, ast.Global):
            if self.s.kind_of(e.name) == "constant":
                c = self.s.constants[e.name].value
                return asm_string(c.value) if isinstance(c, ast.Str) else e.name
            return e.name     # global variable, object, routine (packed), flag, P?prop
        raise TypeError(e)

    def operands(self, exprs: list) -> tuple[list[str], list[str]]:
        """Tokens for each operand, evaluating complex ones in order.
        All but the LAST complex operand go to temporaries (see module doc)."""
        complex_positions = [i for i, e in enumerate(exprs) if not self.is_simple(e)]
        last = complex_positions[-1] if complex_positions else -1
        tokens, temps = [], []
        for i, e in enumerate(exprs):
            if self.is_simple(e):
                tokens.append(self.value_token(e))
            elif i == last:
                self.compile(e, "sp")
                tokens.append("sp")
            else:
                t = self.temp()
                temps.append(t)
                self.compile(e, t)
                tokens.append(t)
        return tokens, temps

    def dest(self, target) -> str:
        """Where an instruction should store its result for this target."""
        if target is None:
            return SCRATCH
        if target is RETURN:
            return "sp"
        return target

    def finish(self, target) -> None:
        """After storing into dest(target): return it if that was the goal."""
        if target is RETURN:
            self.emit("ret_popped")

    def deliver(self, token: str, target) -> None:
        """Send an operand token to the target."""
        if target is None:
            if token == "sp":
                self.emit(f"pull {SCRATCH}")   # keep the stack balanced
        elif target is RETURN:
            self.emit({"1": "rtrue", "0": "rfalse"}.get(token, f"ret {token}"))
        elif token != target:
            if target == "sp":
                self.emit(f"push {token}")
            elif token == "sp":
                self.emit(f"pull {target}")
            else:
                self.emit(f"store {target} {token}")

    def statement_done(self, target) -> None:
        """Statements (TELL, MOVE, ...) have the value TRUE in ZIL."""
        if target is not None:
            self.deliver("1", target)

    # ============================================================ expressions
    def compile(self, e, target) -> None:
        if self.is_simple(e):
            self.deliver(self.value_token(e), target)
        elif isinstance(e, ast.Call):
            self.call(e, target)
        elif isinstance(e, ast.Cond):
            self.cond(e, target)
        elif isinstance(e, ast.Repeat):
            self.repeat(e, target)
        elif isinstance(e, ast.Do):
            self.do(e, target)
        elif isinstance(e, ast.MapContents):
            self.map_contents(e, target)
        elif isinstance(e, ast.Prog):
            self.prog(e, target)
        elif isinstance(e, ast.Tell):
            self.tell(e.items)
            self.statement_done(target)
        elif isinstance(e, ast.Zop):
            self.zop(e, target)
        elif isinstance(e, ast.Atom):
            self.error(e, f"bare atom {e.name} is not a value")
        else:
            raise TypeError(f"cannot compile {type(e).__name__}")

    def call(self, e: ast.Call, target) -> None:
        """<NAME args...>: a predicate, a table-driven built-in, a special
        form with its own method (SPECIAL_FORMS), or a routine call."""
        name = e.name
        if name in PREDICATES and name not in PREDICATES_ONLY_IN_CONDITIONS:
            self.predicate_value(e, target)
        elif name in VALUE_OPS:                 # simple "opcode args -> result"
            tokens, temps = self.operands(e.args)
            self.emit(f"{VALUE_OPS[name]} {' '.join(tokens)} -> {self.dest(target)}")
            self.free(temps)
            self.finish(target)
        elif name in ARITHMETIC:
            self.arithmetic(e, target)
        elif name in STATEMENT_OPS:             # simple "opcode args", value TRUE
            tokens, temps = self.operands(e.args)
            self.emit(f"{STATEMENT_OPS[name]} {' '.join(tokens)}".rstrip())
            self.free(temps)
            self.statement_done(target)
        elif name in SPECIAL_FORMS:
            SPECIAL_FORMS[name](self, e, target)
        elif name in self.s.routines:
            self.routine_call(ast.Global(name, e.loc), e.args, target)
        else:
            self.error(e, f"cannot compile <{name} ...>")

    def predicate_value(self, e: ast.Call, target) -> None:
        """A predicate used as a VALUE: branch, then deliver 1 or 0."""
        if target is None:                      # evaluate for side effects only
            after = self.new_label()
            self.compile_cond(e, after, True)
            self.place(after)
            return
        yes, done = self.new_label(), self.new_label()
        self.compile_cond(e, yes, True)
        self.deliver("0", target)
        if target is not RETURN:
            self.emit(f"jump {done}")
        self.place(yes)
        self.deliver("1", target)
        self.place(done)

    # -- special forms: one small method each (see SPECIAL_FORMS below) ------
    def form_set(self, e: ast.Call, target) -> None:
        """<SET X value> / <SETG X value>: the value of the form is the value."""
        var = self.variable(e.args[0])
        self.compile(e.args[1], var)
        if target is not None:
            self.deliver(var, target)

    def form_inc_dec(self, e: ast.Call, target) -> None:
        var = self.variable(e.args[0])
        self.emit(f"{e.name.lower()} {var}")        # §15 inc/dec take a variable NUMBER
        if target is not None:
            self.deliver(var, target)

    def form_first_next(self, e: ast.Call, target) -> None:
        """FIRST?/NEXT? as a value: §15 get_child/get_sibling store AND branch;
        we branch to the very next instruction."""
        tokens, temps = self.operands(e.args)
        after = self.new_label()
        opcode = "get_child" if e.name == "FIRST?" else "get_sibling"
        self.emit(f"{opcode} {tokens[0]} -> {self.dest(target)} ?{after}")
        self.place(after)
        self.free(temps)
        self.finish(target)

    def form_read(self, e: ast.Call, target) -> None:
        """<READ text [parse]> is §15 aread; in v5 it stores the terminator."""
        args = e.args if len(e.args) == 2 else e.args + [ast.Num(0, e.loc)]
        tokens, temps = self.operands(args)
        self.emit(f"aread {' '.join(tokens)} -> {self.dest(target)}")
        self.free(temps)
        self.finish(target)

    def form_return_now(self, e: ast.Call, target) -> None:
        self.emit({"RTRUE": "rtrue", "RFALSE": "rfalse", "RFATAL": "ret 2"}[e.name])

    def form_again(self, e: ast.Call, target) -> None:
        self.emit(f"jump {self.loops[-1][0]}")

    def form_quit_restart(self, e: ast.Call, target) -> None:
        self.emit(e.name.lower())

    def form_save_restore(self, e: ast.Call, target) -> None:
        self.emit(f"{e.name.lower()} -> {self.dest(target)}")
        self.finish(target)

    def form_apply(self, e: ast.Call, target) -> None:
        self.routine_call(e.args[0], e.args[1:], target)

    def form_printi(self, e: ast.Call, target) -> None:
        if isinstance(e.args[0], ast.Str):
            self.emit(f"print {asm_string(e.args[0].value)}")
        else:
            self.error(e, 'PRINTI takes a literal "string"')
        self.statement_done(target)

    def variable(self, e) -> str:
        """The variable token named by SET/SETG/INC/DEC's first argument."""
        name = e.name
        return "." + name if self.r and name in self.r.local_names() else name

    def arithmetic(self, e: ast.Call, target) -> None:
        opcode = ARITHMETIC[e.name]
        args = e.args
        if e.name == "-" and len(args) == 1:     # <- x> is negation: 0 - x
            args = [ast.Num(0, e.loc), args[0]]
        if len(args) == 1:
            self.compile(args[0], target)
            return
        while len(args) > 2:                    # <+ a b c> == <+ <+ a b> c>
            args = [ast.Call(e.name, args[:2], e.loc)] + args[2:]
        tokens, temps = self.operands(args)
        self.emit(f"{opcode} {tokens[0]} {tokens[1]} -> {self.dest(target)}")
        self.free(temps)
        self.finish(target)

    def routine_call(self, routine, args: list, target) -> None:
        """§15 call_*: pick the shortest form for the argument count."""
        tokens, temps = self.operands([routine] + list(args))
        n = len(args)
        if target is None:
            opcode = "call_1n" if n == 0 else "call_2n" if n == 1 else \
                "call_vn" if n <= 3 else "call_vn2"
            self.emit(f"{opcode} {' '.join(tokens)}")
        else:
            opcode = "call_1s" if n == 0 else "call_2s" if n == 1 else \
                "call_vs" if n <= 3 else "call_vs2"
            self.emit(f"{opcode} {' '.join(tokens)} -> {self.dest(target)}")
            self.finish(target)
        self.free(temps)

    def return_(self, e: ast.Call, target=None) -> None:
        """<RETURN [value]>: leaves the innermost PROG/loop, or else the routine."""
        value = e.args[0] if e.args else ast.Num(1, e.loc)
        if self.loops:
            _start, end, target = self.loops[-1]
            self.compile(value, target)
            if target is not RETURN:
                self.emit(f"jump {end}")
        else:
            self.compile(value, RETURN)

    def zop(self, e: ast.Zop, target) -> None:
        op = BY_NAME[e.opcode]
        tokens, temps = self.operands(e.args)
        text = f"{op.name} {' '.join(tokens)}".rstrip()
        if op.store:
            text += f" -> {self.dest(target)}"
        after = None
        if op.branch:
            after = self.new_label()
            text += f" ?{after}"
        self.emit(text)
        if after:
            self.place(after)
        self.free(temps)
        if op.store:
            self.finish(target)
        else:
            self.statement_done(target)

    def tell(self, items: list) -> None:
        """TELL: merge neighbouring strings and CRs into one `print`."""
        text: list[str] = []

        def flush():
            if text:
                self.emit(f"print {asm_string(''.join(text))}")
                text.clear()

        for item in items:
            if item[0] == "str":
                text.append(item[1])
            elif item[0] == "cr":
                text.append("\n")
            else:
                flush()
                opcode = {"num": "print_num", "obj": "print_obj", "char": "print_char",
                          "addr": "print_addr", "paddr": "print_paddr"}[item[0]]
                tokens, temps = self.operands([item[1]])
                self.emit(f"{opcode} {tokens[0]}")
                self.free(temps)
        flush()

    # ========================================================= control flow
    def cond(self, e: ast.Cond, target) -> None:
        end = self.new_label()
        for test, body in e.clauses:
            nxt = self.new_label()
            if test is None:                         # ELSE / T
                self.body(body, target)
                self.place(nxt)
                break
            if not body:                             # (test) - its value is the result
                t = self.temp()
                self.compile(test, t)
                self.emit(f"jz {t} ?{nxt}")
                self.deliver(t, target)
                self.free([t])
            else:
                self.compile_cond(test, nxt, False)
                self.body(body, target)
            if target is not RETURN:
                self.emit(f"jump {end}")
            self.place(nxt)
        else:
            if target is not None:                   # no clause matched -> false
                self.deliver("0", target)
        self.place(end)

    def body(self, exprs: list, target) -> None:
        for x in exprs[:-1]:
            self.compile(x, None)
        if exprs:
            self.compile(exprs[-1], target)
        else:
            self.statement_done(target)

    def _loop(self, target, emit_body) -> None:
        start, end = self.new_label(), self.new_label()
        self.loops.append((start, end, target))
        self.place(start)
        emit_body(start, end)
        self.loops.pop()
        self.place(end)

    def repeat(self, e: ast.Repeat, target) -> None:
        for name, init in e.bindings:
            if init is not None:
                self.compile(init, "." + name)

        def emit_body(start, end):
            for x in e.body:
                self.compile(x, None)
            self.emit(f"jump {start}")
        self._loop(target, emit_body)

    def prog(self, e: ast.Prog, target) -> None:
        """<PROG (bindings) body...>: a block whose value is its last form.
        RETURN leaves it with a value and AGAIN restarts the body (the
        bindings are NOT re-initialised). BIND is the same block without
        being a RETURN/AGAIN target - they pass through to the enclosing one."""
        for name, init in e.bindings:          # every binding starts fresh
            self.compile(init if init is not None else ast.Num(0, e.loc), "." + name)
        if e.kind == "BIND":
            self.body(e.body, target)
            return
        start, end = self.new_label(), self.new_label()
        self.loops.append((start, end, target))
        self.place(start)
        self.body(e.body, target)
        self.loops.pop()
        self.place(end)

    def do(self, e: ast.Do, target) -> None:
        """<DO (I start end step) ...>: end is INCLUSIVE."""
        var = "." + e.var
        self.compile(e.start, var)
        limit = self.temp()
        self.compile(e.end, limit)

        def emit_body(start, end):
            # the loop starts at `start` = the test
            self.emit(("jg" if e.step > 0 else "jl") + f" {var} {limit} ?{end}")
            for x in e.body:
                self.compile(x, None)
            self.emit(f"add {var} {e.step} -> {var}")
            self.emit(f"jump {start}")
        self._loop(target, emit_body)
        self.free([limit])
        self.statement_done(target)

    def map_contents(self, e: ast.MapContents, target) -> None:
        """<MAP-CONTENTS (I ,BOX) ...>: I walks BOX's children. The NEXT child
        is fetched BEFORE the body runs, so the body may MOVE I safely."""
        var, nxt = "." + e.var, self.temp()
        tokens, temps = self.operands([e.container])
        first = self.new_label()
        self.emit(f"get_child {tokens[0]} -> {var} ?{first}")
        self.place(first)
        self.free(temps)

        def emit_body(start, end):
            self.emit(f"jz {var} ?{end}")
            after = self.new_label()
            self.emit(f"get_sibling {var} -> {nxt} ?{after}")
            self.place(after)
            for x in e.body:
                self.compile(x, None)
            self.emit(f"store {var} {nxt}")
            self.emit(f"jump {start}")
        self._loop(target, emit_body)
        self.free([nxt])
        self.statement_done(target)

    # =========================================================== conditions
    def compile_cond(self, e, label: str, jump_if: bool) -> None:
        """Jump to `label` if e's truth value == jump_if; else fall through."""
        if isinstance(e, ast.False_) or (isinstance(e, ast.Num) and e.value == 0):
            if not jump_if:
                self.emit(f"jump {label}")
            return
        if (isinstance(e, ast.Atom) and e.name == "T") or \
                (isinstance(e, ast.Num) and e.value != 0):
            if jump_if:
                self.emit(f"jump {label}")
            return
        if isinstance(e, ast.Call) and e.name in PREDICATES:
            PREDICATES[e.name](self, e, label, jump_if)
            return
        if isinstance(e, ast.Zop) and BY_NAME[e.opcode].branch and not BY_NAME[e.opcode].store:
            tokens, temps = self.operands(e.args)
            self.emit(f"{e.opcode} {' '.join(tokens)} {self.branch(label, jump_if)}")
            self.free(temps)
            return
        # any other value: true when non-zero
        tokens, temps = self.operands([e])
        self.emit(f"jz {tokens[0]} {self.branch(label, not jump_if)}")
        self.free(temps)

    def simple_branch(self, opcode: str, e, label: str, jump_if: bool) -> None:
        tokens, temps = self.operands(e.args)
        self.emit(f"{opcode} {' '.join(tokens)} {self.branch(label, jump_if)}")
        self.free(temps)

    def equal(self, e, label: str, jump_if: bool) -> None:
        """EQUAL? a b c ...: one je takes a + up to 3 others (§15 je)."""
        first, others = e.args[0], e.args[1:]
        if len(others) <= 3:
            self.simple_branch("je", e, label, jump_if)
            return
        tokens, temps = self.operands([first])
        a = tokens[0]
        if a == "sp":                           # we need it several times
            a = self.temp()
            temps.append(a)
            self.emit(f"pull {a}")
        skip = self.new_label()
        for i in range(0, len(others), 3):
            chunk, ctemps = self.operands(others[i:i + 3])
            self.emit(f"je {a} {' '.join(chunk)} ?{label if jump_if else skip}")
            self.free(ctemps)
        if not jump_if:
            self.emit(f"jump {label}")
        self.place(skip)
        self.free(temps)

    def and_(self, e, label: str, jump_if: bool) -> None:
        if not jump_if:
            for a in e.args:
                self.compile_cond(a, label, False)
            return
        skip = self.new_label()
        for a in e.args[:-1]:
            self.compile_cond(a, skip, False)
        self.compile_cond(e.args[-1], label, True)
        self.place(skip)

    def or_(self, e, label: str, jump_if: bool) -> None:
        if jump_if:
            for a in e.args:
                self.compile_cond(a, label, True)
            return
        skip = self.new_label()
        for a in e.args[:-1]:
            self.compile_cond(a, skip, True)
        self.compile_cond(e.args[-1], label, False)
        self.place(skip)

    def child_test(self, e, label: str, jump_if: bool) -> None:
        tokens, temps = self.operands(e.args)
        opcode = "get_child" if e.name == "FIRST?" else "get_sibling"
        self.emit(f"{opcode} {tokens[0]} -> {SCRATCH} {self.branch(label, jump_if)}")
        self.free(temps)


# ------------------------------------------------------------ built-in tables
def _neg(opcode: str):
    """A predicate that is the OPPOSITE of an opcode: G=? is 'not jl'."""
    return lambda g, e, label, jump_if: g.simple_branch(opcode, e, label, not jump_if)


def _op(opcode: str):
    return lambda g, e, label, jump_if: g.simple_branch(opcode, e, label, jump_if)


PREDICATES = {
    "EQUAL?": CodeGenerator.equal, "=?": CodeGenerator.equal, "==?": CodeGenerator.equal,
    "N=?": lambda g, e, lab, j: g.equal(e, lab, not j),
    "N==?": lambda g, e, lab, j: g.equal(e, lab, not j),
    "G?": _op("jg"), "L?": _op("jl"), "G=?": _neg("jl"), "L=?": _neg("jg"),
    "ZERO?": _op("jz"), "0?": _op("jz"),
    "1?": lambda g, e, lab, j: g.equal(ast.Call("EQUAL?", [e.args[0], ast.Num(1, e.loc)],
                                                e.loc), lab, j),
    "T?": lambda g, e, lab, j: g.compile_cond(e.args[0], lab, j),
    "FSET?": _op("test_attr"), "IN?": _op("jin"),
    "NOT": lambda g, e, lab, j: g.compile_cond(e.args[0], lab, not j),
    "AND": CodeGenerator.and_, "OR": CodeGenerator.or_,
    "VERIFY": _op("verify"),
    "FIRST?": CodeGenerator.child_test, "NEXT?": CodeGenerator.child_test,
}
# FIRST?/NEXT? are VALUES too - in value context codegen.call handles them first
PREDICATES_ONLY_IN_CONDITIONS = {"FIRST?", "NEXT?"}

ARITHMETIC = {"+": "add", "-": "sub", "*": "mul", "/": "div", "MOD": "mod",
              "BAND": "and", "BOR": "or"}

VALUE_OPS = {
    "BCOM": "not", "RANDOM": "random", "GET": "loadw", "GETB": "loadb",
    "GETP": "get_prop", "GETPT": "get_prop_addr", "PTSIZE": "get_prop_len",
    "NEXTP": "get_next_prop", "LOC": "get_parent", "INPUT": "read_char",
}

STATEMENT_OPS = {
    "PRINT": "print_paddr", "PRINTN": "print_num", "PRINTD": "print_obj",
    "PRINTC": "print_char", "PRINTB": "print_addr", "CRLF": "new_line",
    "MOVE": "insert_obj", "REMOVE": "remove_obj", "FSET": "set_attr",
    "FCLEAR": "clear_attr", "PUTP": "put_prop", "PUT": "storew", "PUTB": "storeb",
    "LEX": "tokenise", "SPLIT": "split_window", "SCREEN": "set_window",
    "CURSET": "set_cursor", "HLIGHT": "set_text_style", "CLEAR": "erase_window",
    "COLOR": "set_colour", "BUFOUT": "buffer_mode",
}

SPECIAL_FORMS = {
    "SET": CodeGenerator.form_set, "SETG": CodeGenerator.form_set,
    "INC": CodeGenerator.form_inc_dec, "DEC": CodeGenerator.form_inc_dec,
    "FIRST?": CodeGenerator.form_first_next, "NEXT?": CodeGenerator.form_first_next,
    "READ": CodeGenerator.form_read,
    "RTRUE": CodeGenerator.form_return_now, "RFALSE": CodeGenerator.form_return_now,
    "RFATAL": CodeGenerator.form_return_now, "RETURN": CodeGenerator.return_,
    "AGAIN": CodeGenerator.form_again,
    "QUIT": CodeGenerator.form_quit_restart, "RESTART": CodeGenerator.form_quit_restart,
    "SAVE": CodeGenerator.form_save_restore, "RESTORE": CodeGenerator.form_save_restore,
    "APPLY": CodeGenerator.form_apply, "PRINTI": CodeGenerator.form_printi,
}
